name: Deploy on AWS

on:
  push:
    branches: ["main"]

jobs:
  dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment: dev 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo Somya
        run: echo "Hello Somya"
        
  dev-two:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment: dev 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo Dheeraj
        run: echo "Hello Dheeraj"
